### ISSUE TITLE
Dracula theme missing icons

### ISSUE THREAD

**Issue by SephGER** [mimugmail/opn-repo#202]
Hi,
after activating the Dracula theme my dashboard is missing some icons:
![grafik](https://github.com/mimugmail/opn-repo/assets/2600864/e4281742-4d84-406c-a42f-6a99c66f96d2)

I found out that the Font-Awesome v4-shims.min.css is overwriting the default font with a wrong unicode symbol:

v4-shims.min.css (Line 444):
```css
.fa.fa-exchange::before
{
  content: "\f362";
}
```

font-awesome.min.css (Line 839):
```css
.fa-arrow-right-arrow-left::before, .fa-exchange::before
{
  content: "\f0ec";
}
```

If i change the css to use the default font-awesome code (\f0ec) it works

![grafik](https://github.com/mimugmail/opn-repo/assets/2600864/475412a5-fcb4-4cf1-b9e7-5121700bf359)
